server:
  port: 8050
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
        preferIpAddress: true