spring:
  application:
    name: authority-server
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
eureka:
  client:
    enabled: false
    fetchRegistry: false
    registerWithEureka: false

  instance:
    preferIpAddress: true
server:
  port: 8050
