server:
  port: 8051

spring:
  application:
    name: authority-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${EUREKA_SERVER_PORT}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

api:
  book-user: http://localhost:8061

logging:
  file:
    path: ${user.dir}/logs/${spring.application.name}
