server:
  port: 8050

spring:
  application:
    name: authority-server

eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/

api:
  book-user: http://${EUREKA_SERVER_HOSTNAME}:8060