eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

api:
  book-user: http://localhost:8061

logging:
  file:
    path: ${user.dir}/logs/${spring.application.name}
