server:
  port: 8051

spring:
  application:
    name: authority-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

api:
  book-user: http://localhost:8061

logging:
  file:
    path: logs/${spring.application.name}