server:
  port: 8051
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      instance:
        preferIpAddress: true