server:
  port: 8050

spring:
  application:
    name: authority-server

eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://133.186.153.195:8761/eureka/

api:
  book-user: http://133.186.153.195:8060