spring:
  application:
    name: authority-server
  profiles:
    active: ci
eureka:
  client:
    enabled: false
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true
